import("konoha.ns");

const MtdCreateDBNode = "CreateDBNode";
const MtdDeleteDBNode = "DeleteDBNode";
const MtdUpdateDBNode = "UpdateDBNode";
const MtdInsertLink   = "InsertLink";
const MtdDeleteLink   = "DeleteLink";
const MtdUpdateLink   = "UpdateLink";

const JsonKeyDBNodeType = "DBNodeType";
const JsonKeyCommitLog  = "CommitLog";

const NodeTypeGoal     = "Goal";
const NodeTypeStrategy = "Strategy";
const NodeTypeContext  = "Context";
const NodeTypeEvidence = "Evidence";
